// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package foo

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeBar() *MyBar {
	myFoo := provideMyFoo()
	myBar := NewBar(myFoo)
	return myBar
}

// wire.go:

func provideMyFoo() *MyFoo {
	b := new(MyFoo)
	*b = "Hello, World!"
	return b
}

var Set = wire.NewSet(wire.Bind(new(Foo), new(*MyFoo)), provideMyFoo,
	NewBar,
)
