// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package foo

// Injectors from wire.go:

func InitializeBar(foo Foo) *MyBar {
	myBar := NewBar(foo)
	return myBar
}
